### ISSUE TITLE
Master has a broken build and we need a new version

### ISSUE THREAD

**Issue by func0der** [prolic/HumusAmqp#107]
Hi,

I am not 100% sure why the build is broken. Can not see anything in the logs.
Could you re-trigger it and if it does not fail, can we have a 2.2, please? I would love that psr/log version widening.

**Comment by func0der** [comment]
@prolic ?

**Comment by prolic** [comment]
I am looking at it right now and tests seem to hang on `HumusTest\Amqp\AmqpExtension\JsonRpc\JsonRpcClientAndServerTest::it_sends_requests_and_server_responds`. I'm using PHP 8.2 instead with amqp 2.1.0, maybe I have to downgrade first.

**Comment by basz** [comment]
resolved #110

**Comment by func0der** [comment]
@basz Still don't have a 2.2. F me for putting two issues in one, but yeah :D Not fully solved yet.

**Comment by basz** [comment]
@func0der just relaesed 2.2.0...
